# Generated by Django 6.1 on 2026-08-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('rain_mm', models.FloatField(default=0)),
                ('min_humidity', models.FloatField(blank=True, null=True)),
                ('max_humidity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'district', 'mandal'],
                'indexes': [models.Index(fields=['date'], name='records_rai_date_06df36_idx'), models.Index(fields=['district'], name='records_rai_distric_7b4135_idx'), models.Index(fields=['mandal'], name='records_rai_mandal_f77d62_idx'), models.Index(fields=['date', 'district'], name='records_rai_date_e9c848_idx')],
            },
        ),
    ]
